// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: application.sql

package database

import (
	"context"
	"database/sql"
	"time"
)

const checkApplicationExistsByName = `-- name: CheckApplicationExistsByName :one
SELECT EXISTS (
    SELECT 1 FROM applications WHERE applications.name = $1 AND applications.project_id = (
      SELECT id FROM projects WHERE projects.id = $2
    )
) AS exists
`

type CheckApplicationExistsByNameParams struct {
	Name string
	ID   int32
}

func (q *Queries) CheckApplicationExistsByName(ctx context.Context, arg CheckApplicationExistsByNameParams) (bool, error) {
	row := q.db.QueryRowContext(ctx, checkApplicationExistsByName, arg.Name, arg.ID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const createApplication = `-- name: CreateApplication :one
INSERT INTO applications (project_id, name, description, repo_url, created_at)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, project_id, name, description, repo_url, created_at
`

type CreateApplicationParams struct {
	ProjectID   int32
	Name        string
	Description sql.NullString
	RepoUrl     sql.NullString
	CreatedAt   time.Time
}

func (q *Queries) CreateApplication(ctx context.Context, arg CreateApplicationParams) (Application, error) {
	row := q.db.QueryRowContext(ctx, createApplication,
		arg.ProjectID,
		arg.Name,
		arg.Description,
		arg.RepoUrl,
		arg.CreatedAt,
	)
	var i Application
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Name,
		&i.Description,
		&i.RepoUrl,
		&i.CreatedAt,
	)
	return i, err
}

const deleteProjectApplicationByName = `-- name: DeleteProjectApplicationByName :one
DELETE FROM applications
WHERE applications.name = $1 AND project_id = (
  SELECT id FROM projects WHERE projects.id = $2
) RETURNING id, project_id, name, description, repo_url, created_at
`

type DeleteProjectApplicationByNameParams struct {
	Name string
	ID   int32
}

func (q *Queries) DeleteProjectApplicationByName(ctx context.Context, arg DeleteProjectApplicationByNameParams) (Application, error) {
	row := q.db.QueryRowContext(ctx, deleteProjectApplicationByName, arg.Name, arg.ID)
	var i Application
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Name,
		&i.Description,
		&i.RepoUrl,
		&i.CreatedAt,
	)
	return i, err
}

const getApplicationByName = `-- name: GetApplicationByName :one
SELECT id, project_id, name, description, repo_url, created_at FROM applications
WHERE applications.name = $1 AND project_id = (
  SELECT id FROM projects WHERE projects.id = $2
) LIMIT 1
`

type GetApplicationByNameParams struct {
	Name string
	ID   int32
}

func (q *Queries) GetApplicationByName(ctx context.Context, arg GetApplicationByNameParams) (Application, error) {
	row := q.db.QueryRowContext(ctx, getApplicationByName, arg.Name, arg.ID)
	var i Application
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Name,
		&i.Description,
		&i.RepoUrl,
		&i.CreatedAt,
	)
	return i, err
}

const getLatestApplicationVersionByApplicationName = `-- name: GetLatestApplicationVersionByApplicationName :one
SELECT av.id, av.application_id, av.version, av.git_hash, av.description, av.created_at FROM application_versions av
JOIN applications a ON av.application_id = a.id
WHERE a.name = $1
ORDER BY av.created_at DESC
LIMIT 1
`

func (q *Queries) GetLatestApplicationVersionByApplicationName(ctx context.Context, name string) (ApplicationVersion, error) {
	row := q.db.QueryRowContext(ctx, getLatestApplicationVersionByApplicationName, name)
	var i ApplicationVersion
	err := row.Scan(
		&i.ID,
		&i.ApplicationID,
		&i.Version,
		&i.GitHash,
		&i.Description,
		&i.CreatedAt,
	)
	return i, err
}

const listAllProjectApplications = `-- name: ListAllProjectApplications :many
SELECT id, project_id, name, description, repo_url, created_at FROM applications
WHERE project_id = (
  SELECT id FROM projects WHERE projects.name = $1
)
`

func (q *Queries) ListAllProjectApplications(ctx context.Context, name string) ([]Application, error) {
	rows, err := q.db.QueryContext(ctx, listAllProjectApplications, name)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Application
	for rows.Next() {
		var i Application
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Name,
			&i.Description,
			&i.RepoUrl,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
