// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: project.sql

package database

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const checkProjectExistsByName = `-- name: CheckProjectExistsByName :one
SELECT EXISTS (
    SELECT 1 FROM projects WHERE name = $1
) AS exists
`

func (q *Queries) CheckProjectExistsByName(ctx context.Context, name string) (bool, error) {
	row := q.db.QueryRowContext(ctx, checkProjectExistsByName, name)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const createProject = `-- name: CreateProject :one
INSERT INTO projects (name, link,  description, created_at)
VALUES ($1, $2, $3, $4)
RETURNING id, name, link, description, created_at
`

type CreateProjectParams struct {
	Name        string
	Link        sql.NullString
	Description sql.NullString
	CreatedAt   time.Time
}

func (q *Queries) CreateProject(ctx context.Context, arg CreateProjectParams) (Project, error) {
	row := q.db.QueryRowContext(ctx, createProject,
		arg.Name,
		arg.Link,
		arg.Description,
		arg.CreatedAt,
	)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Link,
		&i.Description,
		&i.CreatedAt,
	)
	return i, err
}

const createProjectVersion = `-- name: CreateProjectVersion :one
INSERT INTO project_versions (id, project_id, version, description, created_at)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, project_id, version, description, created_at
`

type CreateProjectVersionParams struct {
	ID          uuid.UUID
	ProjectID   int32
	Version     string
	Description sql.NullString
	CreatedAt   time.Time
}

func (q *Queries) CreateProjectVersion(ctx context.Context, arg CreateProjectVersionParams) (ProjectVersion, error) {
	row := q.db.QueryRowContext(ctx, createProjectVersion,
		arg.ID,
		arg.ProjectID,
		arg.Version,
		arg.Description,
		arg.CreatedAt,
	)
	var i ProjectVersion
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Version,
		&i.Description,
		&i.CreatedAt,
	)
	return i, err
}

const deleteProjectByName = `-- name: DeleteProjectByName :exec
DELETE FROM projects
WHERE name = $1
`

func (q *Queries) DeleteProjectByName(ctx context.Context, name string) error {
	_, err := q.db.ExecContext(ctx, deleteProjectByName, name)
	return err
}

const getLatestProjectVersionByProjectName = `-- name: GetLatestProjectVersionByProjectName :one
SELECT id, project_id, version, description, created_at FROM project_versions
  WHERE project_id = (
    SELECT id FROM projects WHERE name = $1
  )
  ORDER BY created_at DESC
LIMIT 1
`

func (q *Queries) GetLatestProjectVersionByProjectName(ctx context.Context, name string) (ProjectVersion, error) {
	row := q.db.QueryRowContext(ctx, getLatestProjectVersionByProjectName, name)
	var i ProjectVersion
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Version,
		&i.Description,
		&i.CreatedAt,
	)
	return i, err
}

const getNVersionsByProjectName = `-- name: GetNVersionsByProjectName :many
SELECT id, project_id, version, description, created_at FROM project_versions
WHERE project_id = (
  SELECT id FROM projects WHERE name = $1
)
ORDER BY created_at DESC
LIMIT $2
`

type GetNVersionsByProjectNameParams struct {
	Name  string
	Limit int32
}

func (q *Queries) GetNVersionsByProjectName(ctx context.Context, arg GetNVersionsByProjectNameParams) ([]ProjectVersion, error) {
	rows, err := q.db.QueryContext(ctx, getNVersionsByProjectName, arg.Name, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ProjectVersion
	for rows.Next() {
		var i ProjectVersion
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Version,
			&i.Description,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getProjectByName = `-- name: GetProjectByName :one
SELECT id, name, link, description, created_at FROM projects
WHERE name = $1
LIMIT 1
`

func (q *Queries) GetProjectByName(ctx context.Context, name string) (Project, error) {
	row := q.db.QueryRowContext(ctx, getProjectByName, name)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Link,
		&i.Description,
		&i.CreatedAt,
	)
	return i, err
}

const listAllProjects = `-- name: ListAllProjects :many
SELECT name FROM projects
`

func (q *Queries) ListAllProjects(ctx context.Context) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, listAllProjects)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var name string
		if err := rows.Scan(&name); err != nil {
			return nil, err
		}
		items = append(items, name)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
