// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: schema.sql

package database

import (
	"context"
)

const initSchema = `-- name: InitSchema :exec
DO $$
BEGIN
  CREATE TABLE IF NOT EXISTS projects (
      id              SERIAL PRIMARY KEY,
      name            TEXT NOT NULL UNIQUE,
      link            TEXT,
      description     TEXT,
      created_at      TIMESTAMPTZ NOT NULL DEFAULT now()
  );

  CREATE TABLE IF NOT EXISTS applications (
      id              SERIAL PRIMARY KEY,
      project_id      INTEGER NOT NULL REFERENCES projects(id) ON DELETE CASCADE,
      name            TEXT NOT NULL,
      description     TEXT,
      repo_url        TEXT,
      created_at      TIMESTAMPTZ NOT NULL DEFAULT now(),

      UNIQUE (project_id, name)
  );

  CREATE TABLE IF NOT EXISTS project_versions (
      id              SERIAL PRIMARY KEY,
      project_id      INTEGER NOT NULL REFERENCES projects(id) ON DELETE CASCADE,
      version         TEXT NOT NULL,
      description     TEXT,
      created_at      TIMESTAMPTZ NOT NULL DEFAULT now(),

      UNIQUE (project_id, version)
  );

  CREATE TABLE IF NOT EXISTS application_versions (
      id              SERIAL PRIMARY KEY,
      application_id  INTEGER NOT NULL REFERENCES applications(id) ON DELETE CASCADE,
      version         TEXT NOT NULL,
      git_hash        TEXT,
      description     TEXT,
      created_at      TIMESTAMPTZ NOT NULL DEFAULT now(),

      UNIQUE (application_id, version)
  );

  CREATE TABLE IF NOT EXISTS project_version_apps (
      project_version_id     INTEGER NOT NULL REFERENCES project_versions(id) ON DELETE CASCADE,
      application_id         INTEGER NOT NULL REFERENCES applications(id) ON DELETE CASCADE,
      application_version_id INTEGER NOT NULL REFERENCES application_versions(id),

      PRIMARY KEY (project_version_id, application_id)
  );

  CREATE INDEX IF NOT EXISTS idx_projects_name ON projects(name);
  CREATE INDEX IF NOT EXISTS idx_projects_id ON projects(id);

  CREATE INDEX IF NOT EXISTS idx_applications_name ON applications(name);
  CREATE INDEX IF NOT EXISTS idx_applications_id ON applications(id);

  CREATE INDEX IF NOT EXISTS idx_project_versions_version ON project_versions(version);
  CREATE INDEX IF NOT EXISTS idx_application_versions_version ON application_versions(version);
END
$$
`

func (q *Queries) InitSchema(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, initSchema)
	return err
}
